# Generated by Django 4.2.23 on 2025-08-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginlog',
            old_name='login_time',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='action',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
