# Generated by Django 4.2.23 on 2025-08-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_login_time_loginlog_timestamp_loginlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
